public class HistoryService {
    public void recordMoveAttempt(final Integer roundNumber, final ApexTankBase tank, final MoveDirectionEnum direction) {

    }

    public void recordAttack(final Integer roundNumber, final ApexTankBase tank, final Point pointToAttack) {

    }

	public void updateMoveStatus(final Integer roundNumber, final ApexTankBase tank, final Boolean moved){
	}

	public void updateAttackStatus(final Integer roundNumber, final ApexTankBase tank, final Boolean hit){
	} 
}
